name: 编译KSUN——SUS内核
run-name: ${{ github.actor }} 正在编译 骁龙865 小米系列内核！🚀 🚀
on:
  workflow_dispatch:
    inputs:
      phone:
        description: '选择手机型号：'
        required: true
        default: '小米10'
        type: choice
        options:
          - 小米10
          - 小米10pro
      susfs:
        description: '是否集成SUSFS'
        required: true
        type: boolean
      version:
        description: '自定义版本名（如perf-xxx）/可为空（则为n0kernel）'
        required: false
        type: string
jobs:
  build_job:
    runs-on: ubuntu-22.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
      CI: "false"
    steps:

      - name: 1.下载编译工具
        run: |
          mkdir -p $GITHUB_WORKSPACE/kernel_workspace
          cd $GITHUB_WORKSPACE/kernel_workspace
          wget -q https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm/releases/download/release-19.1.5/LLVM-ET-Arm-19.1.5-Linux-AArch64.tar.xz
          mkdir -p clang
          tar -xzf LLVM-ET-Arm-19.1.5-Linux-AArch64.tar.xz -C clang

      - name: 2.克隆源码与补丁
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace
          git clone https://github.com/jhchong94/kernel_xiaomi_sm8250_n0kernel --depth=1 android_kernel
          git clone -b nono https://github.com/nobbs00/xiaomi10pro-kernel-autobuild.git src
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b kernel-4.19 --depth=1 susfs

      - name: 3.安装KSUN
        run: |
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs

      - name: 4.集成KSU
        run: |
          ls
          echo "进入源码目录"
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          cp $GITHUB_WORKSPACE/kernel_workspace/src/patches/* .
          patch -p1 < new_defconfig.patch
          patch -p1 < non-kprobes.patch
          # tail -n 10 arch/arm64/configs/vendor/umi_defconfig

      - name: 5.应用susfs补丁
        run: |
          if [ ${{ inputs.susfs }} = true ]; then
            echo "选择集成susfs"
            cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
            echo "复制susfs/kernel_patches/fs/* 的内容"
            cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/fs/* ./fs/
            echo "复制susfs/kernel_patches/include/linux/* 的内容"
            cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/include/linux/* ./include/linux/
            echo "复制susfs内核源码补丁"
            cp $GITHUB_WORKSPACE/kernel_workspace/susfs/kernel_patches/50_add_susfs_in_kernel-4.19.patch .
            echo "执行susfs补丁"
            patch -p1 < 50_add_susfs_in_kernel-4.19.patch || true
            echo "修复"
            patch -p1 < after_patch_fix.patch            
          else
            echo "跳过集成susfs"
          fi
        
      - name: 6.开始构建
        run: |
          export PATH=$GITHUB_WORKSPACE/kernel_workspace/clang/bin:$PATH
          echo "Updated PATH: $PATH"
          clang --version
          
          cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel
          # 自定义版本
          if [ ! -z ${{ inputs.version }} ]; then
            echo "不为空"
            sed -i '$s|echo "\$res"|echo "-${{ inputs.version }}"|' ./scripts/setlocalversion
          else
            echo "字符串为空"
          fi

          if [ ${{ inputs.phone }} = '小米10' ]; then
            echo "选择小米10配置"
            DEFCONFIG=vendor/umi_defconfig
          elif [ ${{ inputs.phone }} = '小米10pro' ]; then
            echo "选择小米10pro配置"
            DEFCONFIG=vendor/cmi_defconfig
          else
            echo "非法内容"
          fi

          echo "当前配置为 $DEFCONFIG"

          make -j$(nproc --all) CC=clang O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-buildroot-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-androideabi- $DEFCONFIG
          make -j8 CC=clang O=out ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- LLVM=1 LLVM_IAS=1 CROSS_COMPILE=aarch64-linux-android- CROSS_COMPILE_ARM32=arm-linux-androideabi-    
      
      - name: 7.查看成果
        run: |
            cd $GITHUB_WORKSPACE/kernel_workspace/android_kernel/out/arch/arm64/boot
            ls
            strings Image | grep "Linux version"
            cp Image $GITHUB_WORKSPACE/kernel_workspace/src/Anykernel/

      - name: 8.上传刷入包
        uses: actions/upload-artifact@v4
        with:
          name: KSUN_SUS_sm8250.zip
          path: kernel_workspace/src/Anykernel/*
          retention-days: 3
